package db

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/jackc/pgx/v5/pgxpool"
)

type postgresMigration struct {
	version int
	name    string
	sql     string
}

var postgresMigrations = []postgresMigration{
	{
		version: 1,
		name:    "create_messages",
		sql: `
CREATE TABLE IF NOT EXISTS messages (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT NOT NULL,
	content TEXT NOT NULL,
	type TEXT NOT NULL,
	timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
	},
	{
		version: 2,
		name:    "create_moderation_audit_log",
		sql: `
CREATE TABLE IF NOT EXISTS moderation_audit_log (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id TEXT NOT NULL,
	username TEXT NOT NULL,
	reason TEXT NOT NULL,
	content_preview TEXT NOT NULL,
	content_length INTEGER NOT NULL,
	timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
	},
	{
		version: 3,
		name:    "index_message_timestamp",
		sql: `
CREATE INDEX IF NOT EXISTS idx_messages_timestamp
	ON messages(timestamp);`,
	},
	{
		version: 4,
		name:    "index_moderation_audit_timestamp",
		sql: `
CREATE INDEX IF NOT EXISTS idx_moderation_audit_log_timestamp
	ON moderation_audit_log(timestamp);`,
	},
	{
		version: 5,
		name:    "add_message_rooms",
		sql: `
ALTER TABLE messages ADD COLUMN IF NOT EXISTS room TEXT NOT NULL DEFAULT 'general';
CREATE INDEX IF NOT EXISTS idx_messages_room_timestamp
	ON messages(room, timestamp);`,
	},
	{
		version: 6,
		name:    "bind_message_and_audit_user_ids",
		sql: `
ALTER TABLE messages ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT '';
ALTER TABLE moderation_audit_log ADD COLUMN IF NOT EXISTS user_id TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_messages_user_id_timestamp
	ON messages(user_id, timestamp) WHERE user_id <> '';`,
	},
}

const postgresMigrationLockSQL = `
SELECT pg_advisory_xact_lock(hashtextextended('chatster:schema-migrations', 0));`

// PostgresDB is the pgxpool-backed repository implementation.
type PostgresDB struct {
	pool *pgxpool.Pool
}

// OpenPostgres parses the DSN, verifies connectivity, and applies migrations.
func OpenPostgres(ctx context.Context, dsn string, minConns, maxConns int32) (*PostgresDB, error) {
	if strings.TrimSpace(dsn) == "" {
		return nil, fmt.Errorf("CHATSTER_POSTGRES_DSN is required when CHATSTER_STORAGE=postgres")
	}
	if minConns < 0 {
		return nil, fmt.Errorf("postgres minimum connections must be non-negative")
	}
	if maxConns < 1 {
		return nil, fmt.Errorf("postgres maximum connections must be positive")
	}
	if maxConns < minConns {
		return nil, fmt.Errorf("postgres maximum connections must be at least the minimum")
	}

	poolConfig, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		// Do not wrap the driver error: parse failures can echo portions of a DSN.
		return nil, fmt.Errorf("parse connection configuration: invalid Postgres DSN")
	}
	poolConfig.MinConns = minConns
	poolConfig.MaxConns = maxConns

	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		return nil, fmt.Errorf("create connection pool: %w", err)
	}
	database := &PostgresDB{pool: pool}
	pingCtx, cancel := context.WithTimeout(ctx, 2*time.Second)
	err = database.PingContext(pingCtx)
	cancel()
	if err != nil {
		_ = database.Close()
		return nil, fmt.Errorf("ping database: %w", err)
	}
	if err := database.runMigrations(ctx); err != nil {
		_ = database.Close()
		return nil, fmt.Errorf("run migrations: %w", err)
	}

	return database, nil
}

func (db *PostgresDB) runMigrations(ctx context.Context) error {
	for _, migration := range postgresMigrations {
		if err := db.applyMigration(ctx, migration); err != nil {
			return err
		}
	}
	log.Println("Postgres database migrations applied successfully")
	return nil
}

func (db *PostgresDB) applyMigration(ctx context.Context, migration postgresMigration) error {
	tx, err := db.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if _, err := tx.Exec(ctx, postgresMigrationLockSQL); err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, `
CREATE TABLE IF NOT EXISTS schema_migrations (
	version INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);`); err != nil {
		return err
	}

	var applied bool
	if err := tx.QueryRow(ctx, "SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE version = $1)", migration.version).Scan(&applied); err != nil {
		return err
	}
	if applied {
		return tx.Commit(ctx)
	}

	if _, err := tx.Exec(ctx, migration.sql); err != nil {
		return err
	}
	if _, err := tx.Exec(ctx, "INSERT INTO schema_migrations(version, name) VALUES($1, $2)", migration.version, migration.name); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// SaveMessage is the compatibility convenience method for callers that do not need a context.
func (db *PostgresDB) SaveMessage(username, content, msgType string) (*Message, error) {
	return db.SaveMessageInRoom(DefaultRoom, username, content, msgType)
}

// SaveMessageInRoom is the compatibility convenience method for callers that do not need a context.
func (db *PostgresDB) SaveMessageInRoom(room, username, content, msgType string) (*Message, error) {
	return db.SaveMessageInRoomContext(context.Background(), room, username, content, msgType)
}

// SaveMessageInRoomContext saves a message for a validated room with a caller context.
func (db *PostgresDB) SaveMessageInRoomContext(ctx context.Context, room, username, content, msgType string) (*Message, error) {
	return db.SaveMessageForUserInRoomContext(ctx, room, "", username, content, msgType)
}

// SaveMessageForUserInRoomContext saves a message with stable identity separate from its display name.
func (db *PostgresDB) SaveMessageForUserInRoomContext(ctx context.Context, room, userID, username, content, msgType string) (*Message, error) {
	room, err := NormalizeRoom(room)
	if err != nil {
		return nil, err
	}
	if msgType == "username" {
		return &Message{
			UserID:    userID,
			Username:  username,
			Content:   content,
			Type:      msgType,
			Room:      room,
			Timestamp: time.Now().UTC(),
		}, nil
	}

	var message Message
	if err := db.pool.QueryRow(ctx, `
INSERT INTO messages(room, user_id, username, content, type)
VALUES($1, $2, $3, $4, $5)
RETURNING id, timestamp`, room, userID, username, content, msgType).Scan(&message.ID, &message.Timestamp); err != nil {
		return nil, err
	}
	message.Username = username
	message.UserID = userID
	message.Content = content
	message.Type = msgType
	message.Room = room
	message.Timestamp = message.Timestamp.UTC()
	return &message, nil
}

// PruneMessagesBefore deletes messages older than cutoff.
func (db *PostgresDB) PruneMessagesBefore(cutoff time.Time) (int64, error) {
	return db.PruneMessagesBeforeContext(context.Background(), cutoff)
}

// PruneMessagesBeforeContext deletes messages older than cutoff with a caller context.
func (db *PostgresDB) PruneMessagesBeforeContext(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := db.pool.Exec(ctx, "DELETE FROM messages WHERE timestamp < $1", cutoff.UTC())
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

// PruneModerationEventsBefore deletes audit events older than cutoff.
func (db *PostgresDB) PruneModerationEventsBefore(cutoff time.Time) (int64, error) {
	return db.PruneModerationEventsBeforeContext(context.Background(), cutoff)
}

// PruneModerationEventsBeforeContext deletes audit events older than cutoff with a caller context.
func (db *PostgresDB) PruneModerationEventsBeforeContext(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := db.pool.Exec(ctx, "DELETE FROM moderation_audit_log WHERE timestamp < $1", cutoff.UTC())
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

// SaveModerationEvent records a rejected input for abuse and debugging audits.
func (db *PostgresDB) SaveModerationEvent(sessionID, username, reason, content string) (*ModerationEvent, error) {
	return db.SaveModerationEventContext(context.Background(), sessionID, username, reason, content)
}

// SaveModerationEventContext records an audit event with a caller context.
func (db *PostgresDB) SaveModerationEventContext(ctx context.Context, sessionID, username, reason, content string) (*ModerationEvent, error) {
	return db.SaveModerationEventForUserContext(ctx, sessionID, "", username, reason, content)
}

// SaveModerationEventForUserContext records a rejected input with its authenticated user when available.
func (db *PostgresDB) SaveModerationEventForUserContext(ctx context.Context, sessionID, userID, username, reason, content string) (*ModerationEvent, error) {
	event := ModerationEvent{
		SessionID:      sessionID,
		UserID:         userID,
		Username:       username,
		Reason:         reason,
		ContentPreview: truncateRunes(content, maxAuditPreviewRunes),
		ContentLength:  utf8.RuneCountInString(content),
	}
	if err := db.pool.QueryRow(ctx, `
INSERT INTO moderation_audit_log(
	session_id, user_id, username, reason, content_preview, content_length
)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, timestamp`, event.SessionID, event.UserID, event.Username, event.Reason, event.ContentPreview, event.ContentLength).Scan(&event.ID, &event.Timestamp); err != nil {
		return nil, err
	}
	event.Timestamp = event.Timestamp.UTC()
	return &event, nil
}

// GetRecentMessages returns recent messages from the default room.
func (db *PostgresDB) GetRecentMessages(limit int) ([]Message, error) {
	return db.GetRecentMessagesInRoom(DefaultRoom, limit)
}

// GetRecentMessagesInRoom returns recent messages for a validated room.
func (db *PostgresDB) GetRecentMessagesInRoom(room string, limit int) ([]Message, error) {
	return db.GetRecentMessagesInRoomContext(context.Background(), room, limit)
}

// GetRecentMessagesInRoomContext returns recent room messages with a caller context.
func (db *PostgresDB) GetRecentMessagesInRoomContext(ctx context.Context, room string, limit int) ([]Message, error) {
	room, err := NormalizeRoom(room)
	if err != nil {
		return nil, err
	}

	rows, err := db.pool.Query(ctx, `
SELECT id, room, user_id, username, content, type, timestamp
FROM messages
WHERE room = $1
ORDER BY timestamp DESC, id DESC
LIMIT $2`, room, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	messages := make([]Message, 0)
	for rows.Next() {
		var message Message
		if err := rows.Scan(&message.ID, &message.Room, &message.UserID, &message.Username, &message.Content, &message.Type, &message.Timestamp); err != nil {
			return nil, err
		}
		message.Timestamp = message.Timestamp.UTC()
		messages = append(messages, message)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	for i, j := 0, len(messages)-1; i < j; i, j = i+1, j-1 {
		messages[i], messages[j] = messages[j], messages[i]
	}
	return messages, nil
}

// PingContext checks Postgres health with a caller context.
func (db *PostgresDB) PingContext(ctx context.Context) error {
	return db.pool.Ping(ctx)
}

// Close releases the Postgres connection pool.
func (db *PostgresDB) Close() error {
	db.pool.Close()
	return nil
}
